---
title: "occupancy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{occupancy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(patchwork)
library(tidyverse)
library(RJSONIO) # for reading JSON
devtools::load_all("~/Documents/Research/Code/ECE")
```

```{R}
load.dataset <- function(filename){
    data <- fromJSON(filename)

    # reformat the data into a data frame with a time index and the data values
    tidx <- data$time$index

    cols <- c()

    mat <- NULL
    for (j in 1:data$n_dim) {
        s <- data$series[[j]]
        v <- NULL
        for (i in 1:data$n_obs) {
            val <- s$raw[[i]]
            if (is.null(val)) {
                v <- c(v, NA)
            } else {
                v <- c(v, val)
            }
        }
        cols <- c(cols, s$label)
        mat <- cbind(mat, v)
    }

    mat <- cbind(tidx, mat)
    colnames(mat) <- c('t', cols)

    df <- as.data.frame(mat)
    return(df)
}

# Load Data
main_directory <- "~/Documents/Research/Code/Analyses/benchmark/TCPD/datasets/"
# FIX: location is hard-coded
directory <- paste0(main_directory, "occupancy/occupancy.json")
occupancy <- load.dataset(directory)
df <- occupancy
```

```{R}
# verify it looks like the paper
ts_plot <- map(paste0("V", 1:4), function(var) {
  ggplot(df, aes_string(x = "t", y = var)) +
    geom_line() +
    labs(
      x = "t",
      y = "Value",
      title = paste("t vs", var)
    ) +
    theme_minimal()
})
ts_plot[[1]] / ts_plot[[2]] / ts_plot[[3]] / ts_plot[[4]]
```

```{R}
# Read Annotations
main_directory <- "~/Documents/Research/Code/Analyses/benchmark/TCPD/"
directory <- paste0(main_directory, "annotations.json")
annotations <- fromJSON(directory)
```

## Analyze Data

### Segmentation

```{R}
plot_mean <- function(X, type = "demean") {
  # strip names
  X_obs <- as.data.frame(X)
  colnames(X_obs) <- paste0("V", 1:ncol(X))
  if (type == "demean") {
    X_mean <- segment_mean(X)
  } else if (type == "desmooth") {
    X_mean <- smooth_mean(X)
  }
  colnames(X_mean) <- paste0("V", 1:ncol(X), "_mean")
  X_plot <- bind_cols(
    tibble(index = seq_len(nrow(X_obs))),
    X_obs,
    X_mean
  )

  # pivot longer
  df_long <- X_plot %>%
    pivot_longer(
      cols      = -index,
      names_to  = "variable",
      values_to = "value"
    ) %>%
    mutate(
      type = if_else(str_detect(variable, "_mean$"), "mean", "obs"),
      var  = str_replace(variable, "_mean$", "")
    )

  # plot
  ggplot() +
    # observed lines (thin, black)
    geom_line(
      data = df_long %>% filter(type == "obs"),
      aes(x = index, y = value),
      color = "black",
      linewidth = 0.5
    ) +
    # mean lines (thick, red)
    geom_line(
      data = df_long %>% filter(type == "mean"),
      aes(x = index, y = value),
      color = "red",
      linewidth = 1.2
    ) +
    facet_wrap(
      ~var,
      ncol   = ncol(X_obs),
      scales = "free_y"
    ) +
    labs(
      x     = "Index",
      y     = "Value",
      title = ""
    ) +
    theme_minimal()
}

X <- df[,-1]
plot_mean(X, type = "demean")
```


```{R}
# apply demean
X_segment <- segment_mean(df[, -1])
X_demean <- df[, -1] - X_segment
```

```{R}
cor.pval <- function(X, Y = NULL) {
  if (is.null(Y) & (is.matrix(X) || is.data.frame(X))) {
    mat <- matrix(NA, ncol = ncol(X), nrow = ncol(X))
    for (i in 1:ncol(X)) {
      for (j in 1:ncol(X)) {
        mat[i, j] <- cor.test(X[, i], X[, j])$p.value
      }
    }
    return(mat)
  } else {
    cor.test(X, Y)$p.value
  }
}
ece.pval <- function(X, Y = NULL) {
  if (is.null(Y) & (is.matrix(X) || is.data.frame(X))) {
    mat <- matrix(NA, ncol = ncol(X), nrow = ncol(X))
    for (i in 1:ncol(X)) {
      for (j in 1:ncol(X)) {
        mat[i, j] <- ece.test(X[, i], X[, j])$p.value
      }
    }
    return(mat)
  } else {
    cor.test(X, Y)$p.value
  }
}
```

```{R}
# Big Stinky Problem
cor.pval(X - segment_mean(X)) %>% round(2)
ece.pval(X)

ece.test(df[,2], df[,3])
ece.test(df[,2], df[,4])
```

#### Diagnostics
- auto-correlation
- residual plot

```{R}
plot_residual <- function() {

}

plot_acf <- function() {

}
```

### Smoothing

```{R}
plot_mean(X, type = "desmooth")
```

### Annotator-Oracle
- choose annotation randomly

```{R}
# apply demean
X_segment <- segment_mean(df[, -1])
X_demean <- df[, -1] - X_segment

# apply desmooth
X_smooth <- smooth_mean(df[, -1])
X_desmooth <- df[, -1] - X_smooth


# apply ECE
```

## Produce Tables

