---
title: "simulate-scenarios"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simulate-scenarios}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Simulate Scenarios

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
# Load Libraries
devtools::load_all()
library(patchwork) #
library(tidyverse)

export_power_file <- "~/Documents/Research/Code/ECE/dev/power-sims.csv"
export_est_file <- "~/Documents/Research/Code/ECE/dev/est-sims.csv"
```

```{R, echo=FALSE}
# Plot Scenarios
p1 <- plot_scenario(scenario(1, n = 1000))
p2 <- plot_scenario(scenario(2, n = 1000))
p3 <- plot_scenario(scenario(3, n = 1000))
p4 <- plot_scenario(scenario(4, n = 1000))
p5 <- plot_scenario(scenario(5, n = 1000))
p6 <- plot_scenario(scenario(6, n = 1000))
p7 <- plot_scenario(scenario(7, n = 1000))
p8 <- plot_scenario(scenario(8, n = 1000))
p9 <- plot_scenario(scenario(9, n = 1000))
p10 <- plot_scenario(scenario(10, n = 1000))
p11 <- plot_scenario(scenario(11, n = 1000))

# Show Results
p1 | p2
p3 | p4
p5 | p6
p7 | p8
p9 | p10
p11
```

## Simulate Data

```{R, echo=FALSE}
# Set Simulation Parameters
param_grid <- expand.grid(
  scenario = 1:11,
  method = c("ECE", "demean", "desmooth"),
  sxy = seq(0, 0.5, 0.05),
  sx = 1,
  sy = 1,
  n = c(200, 1000),
  n_sim = 1000
)
```

```{R, eval=FALSE, echo=FALSE}
# Simulate Power Results
progress_ct <- 0 # global counter
sim_power <- pmap_dfr(
  param_grid,
  function(scenario, method, sxy, sx, sy, n, n_sim) {
    progress_ct <<- progress_ct + 1 # update counter
    message("Running: ", progress_ct, "/", nrow(param_grid))
    params <- scenario(
      scenario_num = scenario,
      sxy = sxy,
      sx = sx,
      sy = sy,
      n = n
    )
    power <- simulate_power(params, method = method, n_sim = n_sim)
    export_power_simulations(power, method, params, n_sims, export_power_file)
    tibble(scenario, method, n, n_sim, power)
  }
)
```

```{R, eval=FALSE, echo=FALSE}
# Simulate Estimate Results
progress_ct <- 0 # global counter
sim_est <- pmap_dfr(
  param_grid,
  function(scenario, method, sxy, sx, sy, n, n_sim) {
    progress_ct <<- progress_ct + 1 # update counter
    message("Running: ", progress_ct, "/", nrow(param_grid))
    params <- scenario(
      scenario_num = scenario,
      sxy = sxy,
      sx = sx,
      sy = sy,
      n = n
    )
    est <- simulate_est(params, method = method, n_sim = n_sim)
    export_est_simulations(est, method, params, n_sims, export_est_file)
    tibble(scenario, method, n, n_sim, est)
  }
)
```
