project:
  type: book

book:
  title: "ECE Notes"
  author: "Jeff Mei"
  date: today
  chapters:
    - index.qmd
    - model-assumptions.qmd
    - lagged-differences.qmd
    - bilinear-form.qmd
    - computational-solution.qmd
    - model-misspecification.qmd
    - positive-semidefinite.qmd
    - diagonal-test.qmd
  appendices:
    - math-background.qmd
    - math-results.qmd

format:
  html:
    theme: cosmo
