project:
  type: book

book:
  title: "ECE Notes"
  author: "Jeff Mei"
  date: today
  chapters:
    - index.qmd
    - part: "Estimation"
      chapters:
        - model-assumptions.qmd
        - lagged-differences.qmd
        - bilinear-form.qmd
        - kappa-estimation.qmd
        - omega-estimation.qmd
    - part: "Inference"
      chapters:
        - z-test.qmd
        - multiplier-bootstrap-test.qmd
        - parametric-bootstrap-test.qmd
        - independence-test.qmd
        - confidence-interval.qmd
    - part: "Numerical Studies"
      chapters:
        - simulation.qmd
        - scenarios.qmd
        - competing-methods.qmd
        - type-i-error.qmd
        - power.qmd
        - diagnostics.qmd
    - part: real-data.qmd
      chapters:
        - co2-inhalation.qmd
        - copy-number-variation.qmd
        - labor-productivity.qmd
        - mental-load.qmd
        - elnino.qmd
        - glen-canyon-dam.qmd
        - gps-antenna-offset.qmd
        - air-pollution.qmd
        - secom.qmd
        - steel-industry.qmd
        - interest-rates.qmd
        - wearable-gestures.qmd
        - sleep-polysomnography.qmd
        - detroit-lake-algal-bloom.qmd
        - phillips-curve.qmd
        - oil-price-deregulation.qmd
        - battery-aging.qmd
        - hurricane-michael-buoy.qmd
        - cpi-components.qmd
    - part: "In Progress"
      chapters:
        - positive-semidefinite.qmd
        - model-misspecification.qmd
        - smooth-mean.qmd
        - piecewise-linear.qmd
        - package.qmd
        - partial-correlation.qmd
        - pca.qmd
        - ssa.qmd
  appendices:
    - computational-solution.qmd
    - mean-removal.qmd
    - math-background.qmd
    - math-results.qmd

format:
  html:
    theme: cosmo
