project:
  type: book

book:
  title: "ECE Notes"
  author: "Jeff Mei"
  date: today
  chapters:
    - index.qmd
    - part: "Estimation"
      chapters:
        - model-assumptions.qmd
        - lagged-differences.qmd
        - bilinear-form.qmd
        - kappa-estimation.qmd
    - part: "Inference"
      chapters:
        - z-test.qmd
        - multiplier-bootstrap-test.qmd
        - parametric-bootstrap-test.qmd
        - independence-test.qmd
    - part: "Numerical Studies"
      chapters:
        - simulation.qmd
        - type-i-error.qmd
        - power.qmd
    - part: "Real Data"
      chapters:
        - co2-inhalation.qmd
        - copy-number-variation.qmd
    - part: "In Progress"
      chapters:
        - positive-semidefinite.qmd
        - model-misspecification.qmd
        - package.qmd
        - partial-correlation.qmd
  appendices:
    - computational-solution.qmd
    - mean-removal.qmd
    - math-background.qmd
    - math-results.qmd

format:
  html:
    theme: cosmo
