name: Publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("devtools", "testthat"))
          devtools::install(".", quiet = TRUE)

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
